services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    pull_policy: always
    expose:
      - 5432
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: vaxsul
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    build:
      context: ./vaxsul_backend
      dockerfile: Dockerfile

  client:
    container_name: vaxsul_client
    restart: always
    depends_on:
      - server
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      NEXT_PUBLIC_VAXSUL_SERVER_URL: http://server:8080
    build:
      context: ./vaxsul_frontend
      dockerfile: Dockerfile

networks:
  default:
    name: vaxsul

volumes:
  db_data: null
