ktor:
  application:
    modules:
      - com.github.dannful.ApplicationKt.module
  deployment:
    port: 8080

auth:
  jwt:
    secret: $JWT_STANDARD
    issuer: "http://0.0.0.0:8080/"
    audience: "http://0.0.0.0:8080/"
    realm: "Access to VacSul"
  admin:
    user: $ADMIN_USER
    password: $ADMIN_PASSWORD

db:
  url: $DB_URL
  user: $DB_USER
  password: $DB_PASSWORD
