name: Run CI
on: push
jobs:
  CI:
    services:
      postgresql:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    name: Run CI
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Run tests
        working-directory: ./vaxsul_backend
        env:
          JWT_SECRET: ae1da6c207660e05182bd1cffd92adb58d4b5f7894d6a940344ede142ff46869
          DB_URL: jdbc:pgsql://localhost:5432/test
          DB_USER: postgres
          DB_PASSWORD: postgres
        run: ./gradlew test